### ISSUE TITLE
[Question] Is it still possible to pass None through environment variables?

### ISSUE THREAD

**Issue by eremeevfd** [pydantic/pydantic-settings#199]
It worked in Pydantic 1.* and I've read that we can use ENV_VAR=None|none|null to parse as None in python. Does it still work for pydantic 2.0?
short example:
```python
import os

from pydantic_settings import BaseSettings

class Settings(BaseSettings):
    ENV_VAR: str | None = None

if __name__ == "__main__":
    os.environ["ENV_VAR"] = "None"
    print(Settings().ENV_VAR)  # will be string "None" insted of an actual None
```

**Comment by hramezani** [comment]
Thanks @eremeevfd  for the issue.

> It worked in Pydantic 1.* and I've read that we can use ENV_VAR=None|none|null to parse as None in python.

Where did you read it?

You already provided a value(`None` as a string) for env variable, So, `pydantic-settings` will pick that.
If you don't provide any value for the env, it will use the default value which is `None` in you case.

**Comment by eremeevfd** [comment]
@hramezani Okay, I'm sorry, I think I've mixed topics of boolean parsing (true/True/false/False) with None parsing and somehow thought that null/None from envvar should be parse to None type also 😆 
Everything works as expected and worked this way!

**Comment by eremeevfd** [comment]
@kschwab I think it's better to create new issue with your question or maybe I should reopen this one again?

**Comment by hramezani** [comment]
@kschwab I would suggest adding a new config flag named e.g. `parse_env_none` or something like this.
The default value should be `False` and it means string`'None'` should be considered as string.(to don't introduce breaking change).
By setting the flag to `True`,  string `'None'` should be parse as `None`

**Comment by kschwab** [comment]
@hramezani thanks for the feedback.

My rationale behind using a `str` flag instead of a `bool` flag was when considering compliance with e.g. a [JSON spec](https://www.json.org/json-en.html) `null` value. It may be desirable that users want "null" (str) to be coerced into `None` instead of only "None" (str) to `None`. i.e., the None str parse value is user defined. Defining the flag itself as `None` would be the default so as to not introduce breaking changes.

I actually don't have a strong preference either way. A `bool` flag is simpler and likely the dominant case. Let me know how you would like to proceed. I'll take a stab at initial PR for your feedback.

**Comment by hramezani** [comment]
Agree @kschwab. Let's define it as `str`

**Comment by kschwab** [comment]
@eremeevfd 

As an update, once PR #206 merges, the below will now work:

```python
import os

from pydantic_settings import BaseSettings

class Settings(BaseSettings):
    ENV_VAR: str | None = 'Default string'

if __name__ == '__main__':

    os.environ['ENV_VAR'] = 'None'
    print(type(Settings().ENV_VAR) == type(None))
    '''
    False
    '''

    print(type(Settings(_env_parse_none_str='None').ENV_VAR) == type(None))
    '''
    True
    '''

    os.environ['ENV_VAR'] = 'null'
    print(type(Settings(_env_parse_none_str='null').ENV_VAR) == type(None))
    '''
    True
    '''
```
