### ISSUE TITLE
A clearer `ValidationError` should be provided with `Optional` settings

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [pydantic/pydantic-settings#234]
This is with Pydantic 2.1.0 on Python 3.10+.

```python
from typing import Optional, Literal

from pydantic import Field

from pydantic_settings import BaseSettings

class Settings(BaseSettings):
    sample: Optional[Literal["test", "test2"]] = Field(None,description="test")
```

In the above example, if we do `Settings(sample="invalid")`, the traceback mentions the following:

```
ValidationError: 1 validation error for Settings
sample
  Input should be 'test' or 'test2' [type=literal_error, input_value=1, input_type=int]
    For further information visit https://errors.pydantic.dev/2.5/v/literal_error
```

However, from a user's perspective, this can be confusing because `sample` doesn't only take "test" or "test2" as inputs but also `None`, and this is not mentioned in the returned `ValidationError`.

**Comment by hramezani** [comment]
Thanks @Andrew-S-Rosen for reporting this.

This is not related to `pydantic-settings`. the error message comes from `pydantic`.
BTW, I am unsure whether we should mention `None` here because it is the same for other errors e.g. invalid string.

```py
from typing import Optional

from pydantic import BaseModel


class Settings(BaseModel):
    sample: Optional[str]

Settings(sample=2)
"""
pydantic_core._pydantic_core.ValidationError: 1 validation error for Settings
sample
  Input should be a valid string [type=string_type, input_value=2, input_type=int]
    For further information visit https://errors.pydantic.dev/2.6/v/string_type
"""
```
As you can see it says `Input should be a valid string` and does not mention `None`.

BTW, I closed the issue here and you can create a new issue on [pydantic](https://github.com/pydantic/pydantic) If this answer does not convinced you.

**Comment by Andrew-S-Rosen** [comment]
Thanks, @hramezani! You're totally correct. Apologies for that. I will report upstream.
