### ISSUE TITLE
Interaction with `pydantic-next`

### ISSUE THREAD

**Issue by Kludex** [pydantic/pydantic-settings#28]
How will `pydantic-settings` interact with `pydantic-next`?

**Comment by dmontagu** [comment]
I'm thinking something like, create a module `pydantic_settings._internal.__init__` and do something like:

```python
try:
    import pydantic_next as pydantic
except ImportError:
    import pydantic as pydantic
    if pydantic.__version__ < 2.0:
        raise ImportError("Install pydantic v2")
except ImportError:
    raise ImportError("Install pydantic v2 or pydantic_next")
```
(can tweak the error messages).

Then anywhere in the package that uses pydantic, rather than doing `from pydantic import X` do `from pydantic_settings._internal import pydantic` and `class BaseSettings(pydantic.BaseModel)` etc.

For imports that can't be obtained via attribute access from `pydantic` we could just add more imports in `pydantic_settings._internal` or whatever.

(No strong opinions about the module names or other details, just, I think this approach should work for using whichever of the two makes sense.)

**Comment by Kludex** [comment]
We didn't go for this idea.
