### ISSUE TITLE
support regex to load config that falls under the same roof

### ISSUE THREAD

**Issue by MarcBresson** [pydantic/pydantic-settings#416]
Hello ! It's me again :)

l'm using fsspec to implement a general interface, and I would like our end users to be able to use any storage they want and supply the required connection parameters through env variables.

Because I don't really want to specify all the different models for all the different storage solutions, I thought it would be quite cool to have one BaseSettings model that would capture any env variable that matches a regex. In my case, it would give something like:

```python
from pydantic_settings import BaseSettings, SettingsConfigDict

class A(BaseSettings):
    model_config = SettingsConfigDict(match="STORAGE_*")

    name: str
```

of course it means that this model is also configured with `extra="allow"`

**Comment by MarcBresson** [comment]
maybe it's too similar to `env_nested_delimiter` option, i'll let you be the hudge of that :)

The workaround is to have one nested model like the following:

```python
from pydantic import BaseModel, ConfigDict
from pydantic_settings import BaseSettings, SettingsConfigDict

class StorageParameters(BaseModel):
    model_config = ConfigDict(extra="allow")


class StorageConfig(BaseSettings):
    model_config = SettingsConfigDict(env_nested_delimiter="__")

    storage_name: str
    storage: StorageParameters
```

```python
import os

os.environ["STORAGE_NAME"] = "s3"
os.environ["STORAGE__USERNAME"] = "michel"
os.environ["STORAGE__PASSWORD"] = "1234"
```

```python
StorageConfig()
#> StorageConfig(storage_name='s3', storage=StorageParameters(username='michel', password='1234'))
```

this is not it, but it is close enough

**Comment by hramezani** [comment]
@MarcBresson Thanks for this issue.

I don't think having a `match` configuration for this specific use case makes sense because first it has to be supported in all sources and this is collecting extra fields that the env settings source does not support.

But you can use dot env settings source that collects extra fields. you can simply change the first models to

```py
from pydantic_settings import BaseSettings, SettingsConfigDict

class A(BaseSettings):
    model_config = SettingsConfigDict(extra='allow', env_prefix='STORAGE_', env_file='.env')

    name: str
```

and then by having the `.env` file like:

```
storage_name=test name
storage_foo=bar
```

You will get `{'name': 'test name', 'storage_foo': 'bar'}` in your model.

Hope this workaround helps you!
