### ISSUE TITLE
Add SOPS settings source for secrets

### ISSUE THREAD

**Issue by pavelzw** [pydantic/pydantic-settings#421]
[SOPS](https://github.com/getsops/sops) is a simple and portable way of handling secrets. It would be nice if there was an integrated way of handling sops files similar to `AzureKeyVaultSettingsSource`.

**Comment by hramezani** [comment]
Thanks @pavelzw for requesting this new settings source.

Unfortunately, we can't accept the new source because:

- `pydantic-settings` already has many of the most popular settings sources.
- It increases the code base's complexity and needs more maintenance effort.
- It is possible to [add custom settings source into pydantic-settings](https://docs.pydantic.dev/latest/concepts/pydantic_settings/#adding-sources)
- It is not requested a lot by the community.

BTW, we can reconsider this settings source if there are more people interested in it.

Thanks for your understanding 🙏

**Comment by pavelzw** [comment]
For reference:

I created my own custom settings source, https://github.com/pavelzw/pydantic-settings-sops
